### ISSUE TITLE
HydrateFirestartrTerraformWorkspaces Module

### ISSUE THREAD

**Issue by tonirvega** [prefapp/daggerverse#107]
# Motivation

To deploy new versions of Terraform workspace infrastructure elements, we aim to implement a workflow capable of rendering Firestartr Terraform workspaces. Currently, referential integrity validation is in place, but it should be controlled by a feature flag. This change is necessary because referential integrity validation will be skipped in that repository and instead validated directly on the control plane (controller from firestartr.dev kuberenetes api ) .

### main function `Render()`
```golang
func (m *HydrateFirestartrTerraformWorkspaces) Render(

	ctx context.Context,

	app string,

	azVmss string, // platform

	// +required
	tenant string,

	//+required
	env string,

	// +optional
	// +default="{\"images\":[]}"
	newImagesMatrix string,

)  *dagger.Directory {
 // code...
}
```

## Json pointer file

This file will contain the information about the relation between the image provided by the dispatch interface.

```yaml
workspaces: 
 - name: my-workspace-name # claim name
   image_key: "providers.terraform.values.vmss.run_script.docker_image"
```

# Acceptance Criteria

- [ ] prefapp/gitops-k8s#785
- [x] Code new hydrate terraform workspace module
