### ISSUE TITLE
Create dynamic tags with new releases

### ISSUE THREAD

**Issue by jalvarezit** [prefapp/daggerverse#111]
Actualmente se crean tags siguiendo un modelo de monorepo, es decir, cada vez que se crea una nueva release de uno de los worklfows se crea una tag tal que <package>-vX.Y.Z . Esto fuerza a que los workflows que usen estos módulos de daggerverse tengan que actualizarse constantemente.

Esto choca con la dinámica que se usa tanto en los [workflows reusables](https://github.com/prefapp/firestarter-workflows/tree/main/.github/workflows) como en los workflows instalados a través de [features](https://github.com/prefapp/features). 

Para ello se debería crear adicionalmente una tag que incluya solo la *major version* y sobreescribirla con cada nueva release.

Además debemos tener en cuenta que cuando se vaya a hacer un cambio de interfaz habría que sacar una nueva *major version* para evitar romper la compatibilidad en todos los lugares donde se esté usando.

**Comment by jalvarezit** [comment]
De acuerdo con la documentación oficial de la github action, para actualizar la *major* deberiamos usar los siguientes steps:

```yaml
      - uses: actions/checkout@v4
        if: steps.release.outputs.tag_name != ''
        with:
          ref: ${{ steps.release.outputs.tag_name }}

      - name: Get major version num and update tag
        if: steps.release.outputs.tag_name != ''
        run: |
          git config --global user.name 'Prefapp Bot'
          git config --global user.email 'prefapp-bot@users.noreply.github.com'
          git tag -fa v${{ steps.release.outputs.major }} -m "Update major version tag"
          git push origin v${{ steps.release.outputs.major }} --force
````

En el caso de ser un monorepo tambien es posible pero habría que hacer una lógica adicional ya que en ese caso el resultado de `steps.release.outputs.major` no existiría, en su lugar se obtiene un json al que se accede utilizando el nombre del paquete, es decir si en el mono repo tenemos un paquete *foo* se guardaría en `${{ steps.release.outputs['for--major'] }}'` por tanto esa lógica debería ser capaz de listar los outputs de ese step y pushear por cada uno.
