### ISSUE TITLE
[hydrate-kuberentes] Suppport `image_keys` on chart render

### ISSUE THREAD

**Issue by tonirvega** [prefapp/daggerverse#129]
# Motivation

In order to support multiple chart values interfaces, we would like to include a new key to be processed.

```yaml
deployments:
  - tenant: test-tenant
    platform: cluster-name
    type: snapshots
    flavor: default
    application: sample-app
    env: dev
    service_names: ['micro-a', 'micro-b']
    image_keys: ['/providers/terraform/values/vmss/run_script/docker_image'] # tfworkspace
    image_keys: ['/micro-a/image', '/micro-b/image'] # umbrella chart
    image_keys: ['/spec/containers/0/image'] # raw kubernetes deployment
    version: $branch_main
    state_repo: "firestartr-test/state-app-sample-app"
    registry: 041728615317.dkr.ecr.eu-west-1.amazonaws.com
    image_repository: firestartr-test/build-and-dispatch-images-react
```

The `images.yaml` will be built either from `image_keys` or `service_names` keys.

# Acceptance Criteria

- [ ] Modify current images.yaml builder
- [ ] Tests have been passed
- [ ] Team acceptance
