### ISSUE TITLE
[firestartr-bootstrap] e2e test to validate workflow

### ISSUE THREAD

**Issue by tonirvega** [prefapp/daggerverse#196]
# Motivation

To validate the bootstrap process, we should execute it each time we push to the master branch or when we create a new release. Additionally, it would be beneficial to run it daily.

1. Verify that the specified repositories do not already exist in the firestartr-test organization, and delete them if necessary.
2. Confirm that the <org>-all group does not exist in the firestartr-test organization, and remove it if necessary.
3. Initiate the bootstrap workflow using the specified Bootstrap file:
```yaml
---
firestartr:
  version: "v1.36.7"

org: "firestartr-test"

pushFiles:
  claims:
    push: true
    repo: "e2e-bootstrap-claims"
  crs:
    providers:
      github: 
        push: true
        repo: "e2e-bootstrap-state-github"

components:  

  - name: "dot-firestartr"
    description: "Repository with the terraform code for manage the multi-tenant infrastructure"
    repoName: "e2e-bootstrap-dot-firestartr"
    defaultBranch: main
    features: 
      - name: firestartr_repo
        version: 1.0.0

  - name: "e2e-bootstrap-claims"
    description: "Firestartr configuration folders and files"
    defaultBranch: main
    features: 
      - name: claims_repo
        version: 1.6.1

  - name: "e2e-bootstrap-catalog"
    description: "Firestartr configuration folders and files"
    defaultBranch: main
    features:
      - name: catalog_repo
        version: 1.0.0
    variables:
      - name: FIRESTARTER_PROVIDER
        value: "all"

  - name: "e2e-bootstrap-state-github"
    description: "Firestartr Github wet repository"
    defaultBranch: main
    features: 
      - name: state_github
        version: 1.0.0
    variables:
      - name: CLAIMS_DEFAULT_BRANCH
        value: "main"
      - name: CLAIMS_REPO_NAME
        value: "claims"
      - name: FIRESTARTER_PROVIDER
        value: "github"

  - name: "e2e-bootstrap-state-infra"
    description: "Firestartr Terraform workspaces wet repository"
    defaultBranch: main
    features: 
      - name: state_infra
        version: 1.1.0
    variables:
      - name: CLAIMS_DEFAULT_BRANCH
        value: "main"
      - name: CLAIMS_REPO_NAME
        value: "claims"
      - name: FIRESTARTER_PROVIDER
        value: "terraform"
```
5. Once the workflow finished, we need to ensure the imports were successfully executed in `e2e-bootstrap-claims` and `e2e-bootstrap-state-github` repositories.

# Acceptance Criteria

- [ ] A new github workflow has been coded
- [ ] The github workflow should be executed every day
- [ ] A github batch is configured in the README to check quickly if the last run executed successfully
- [ ] Team acceptance
