### ISSUE TITLE
Improve release process with rolling tags

### ISSUE THREAD

**Issue by alambike** [prefapp/daggerverse#203]
### Motivation

It would be useful to add a rolling tag that can be moved from release to release, by module.

This way, we can reference this tag with the major version of a module in a workflow, without having to move it between minor version changes and patches.

Ex:

```
- name: Hydrate CRs
  uses: dagger/dagger-for-github@v5
  with:
    verb: call
    module: github.com/prefapp/daggerverse/notify-and-hydrate-state@notify-and-hydrate-state-v1.4.1
```

Will be:
```
- name: Hydrate CRs
  uses: dagger/dagger-for-github@v5
  with:
    verb: call
    module: github.com/prefapp/daggerverse/notify-and-hydrate-state@notify-and-hydrate-state-v1

```
